export interface ThreatActor {
  id: string; name: string; aliases: string[]; origin: string;
  type: "nation-state" | "cybercrime" | "hacktivist" | "insider";
  motivation: string; targets: string[]; activeSince: string;
  ttps: string[]; ttpDescriptions: string[]; notableAttacks: string[]; description: string;
}

export const THREAT_ACTORS: ThreatActor[] = [
  { id: "apt29", name: "APT29 (Cozy Bear)", aliases: ["Cozy Bear","Nobelium","Midnight Blizzard"], origin: "Russia (SVR)", type: "nation-state", motivation: "Espionage", targets: ["Government","Defence","Technology","Healthcare"], activeSince: "2008", ttps: ["T1566.001","T1195.002","T1078","T1071.001","T1027","T1550.001","T1098","T1114.002"], ttpDescriptions: ["Spear-phishing with attachments","Supply chain compromise (SolarWinds)","Valid account abuse","C2 over HTTPS","Obfuscated payloads","Token theft for cloud access","Account manipulation","Email collection via API"], notableAttacks: ["SolarWinds (2020)","Microsoft token theft (2023)","DNC hack (2016)"], description: "Russia premier cyber espionage unit. Patient, sophisticated operations targeting Western governments." },
  { id: "apt28", name: "APT28 (Fancy Bear)", aliases: ["Fancy Bear","Sofacy","Forest Blizzard"], origin: "Russia (GRU)", type: "nation-state", motivation: "Espionage, disruption", targets: ["Government","Military","Media","Elections","Energy"], activeSince: "2004", ttps: ["T1566.002","T1190","T1078","T1003.001","T1071.001","T1583.001","T1588.002","T1110"], ttpDescriptions: ["Credential harvesting phishing","Public-facing app exploitation","Stolen credential reuse","LSASS credential dumping","C2 via web services","Lookalike phishing domains","Zero-day exploitation","Brute force VPN/email"], notableAttacks: ["DNC/DCCC hack (2016)","Bundestag breach (2015)","NotPetya (2017)"], description: "GRU military intelligence. Aggressive election interference and destructive attacks." },
  { id: "sandworm", name: "Sandworm", aliases: ["Voodoo Bear","Seashell Blizzard","Iridium"], origin: "Russia (GRU 74455)", type: "nation-state", motivation: "Destruction, sabotage", targets: ["Energy","Critical Infrastructure","Government","Olympics"], activeSince: "2009", ttps: ["T1195.002","T1059.001","T1486","T1485","T1561.002","T1190","T1047"], ttpDescriptions: ["Supply chain compromise","PowerShell attacks","Ransomware (NotPetya)","Wiper malware","Disk wiping","Public-facing exploitation","WMI lateral movement"], notableAttacks: ["NotPetya $10B+ (2017)","Ukraine power grid (2015,2016)","Olympic Destroyer (2018)","Industroyer2 (2022)"], description: "Russia most destructive unit. NotPetya, Ukraine blackouts, Olympics attacks." },
  { id: "apt41", name: "APT41 (Double Dragon)", aliases: ["Wicked Panda","Barium","Winnti"], origin: "China (MSS)", type: "nation-state", motivation: "Espionage + financial gain", targets: ["Technology","Healthcare","Gaming","Telecoms","Manufacturing"], activeSince: "2012", ttps: ["T1195.002","T1190","T1059.001","T1055","T1574.002","T1027","T1071.001"], ttpDescriptions: ["Supply chain via software vendors","Public-facing exploitation","PowerShell execution","Process injection","DLL side-loading","Obfuscated malware","HTTPS C2"], notableAttacks: ["ShadowPad (2017)","CCleaner (2017)","ProxyLogon (2021)"], description: "Dual-mission Chinese APT doing both state espionage and financial cybercrime." },
  { id: "volt-typhoon", name: "Volt Typhoon", aliases: ["Bronze Silhouette","Vanguard Panda"], origin: "China (PLA)", type: "nation-state", motivation: "Infrastructure pre-positioning", targets: ["Critical Infrastructure","Energy","Water","Telecoms","Transport"], activeSince: "2021", ttps: ["T1078","T1059.001","T1218","T1036","T1003","T1046","T1090","T1005"], ttpDescriptions: ["Living-off-the-land with valid creds","PowerShell/cmd execution","LOLBins (ntdsutil, netsh)","Process masquerading","AD credential harvesting","Network scanning","SOHO router proxying","Local data collection"], notableAttacks: ["US critical infrastructure (2023)","Guam military (2023)","KV-botnet"], description: "Chinese group pre-positioning in US critical infrastructure. Almost exclusively LOTL." },
  { id: "salt-typhoon", name: "Salt Typhoon", aliases: ["GhostEmperor","FamousSparrow"], origin: "China", type: "nation-state", motivation: "Telecoms espionage", targets: ["Telecoms","ISPs","Government"], activeSince: "2020", ttps: ["T1190","T1078","T1557","T1040","T1005","T1071","T1048"], ttpDescriptions: ["Telecom exploitation","Valid account compromise","Network interception","Network sniffing","Local data collection","Standard C2","Data exfiltration"], notableAttacks: ["AT&T/Verizon/T-Mobile (2024)","Lawful intercept compromise","Political wiretapping"], description: "Compromised major US telecoms to intercept communications including wiretap systems." },
  { id: "lazarus", name: "Lazarus Group", aliases: ["Hidden Cobra","Diamond Sleet","APT38"], origin: "North Korea (RGB)", type: "nation-state", motivation: "Financial theft, espionage", targets: ["Finance","Cryptocurrency","Defence","Media"], activeSince: "2009", ttps: ["T1566.001","T1204.002","T1059.007","T1195.002","T1486","T1485","T1071.001"], ttpDescriptions: ["Spear-phishing weaponised docs","Fake job offer social engineering","JavaScript/Node.js malware","Supply chain (3CX)","Ransomware deployment","Wiper attacks","Custom HTTPS C2"], notableAttacks: ["Sony Pictures (2014)","Bangladesh Bank $81M (2016)","WannaCry (2017)","3CX (2023)","Ronin $625M (2022)"], description: "North Korea primary cyber unit. Bank heists and crypto theft to fund the regime." },
  { id: "apt33", name: "APT33 (Elfin)", aliases: ["Elfin","Peach Sandstorm","Refined Kitten"], origin: "Iran (IRGC)", type: "nation-state", motivation: "Espionage, destruction", targets: ["Aviation","Energy","Petrochemical","Defence"], activeSince: "2013", ttps: ["T1566.002","T1110","T1078","T1059.001","T1486","T1485"], ttpDescriptions: ["Credential harvesting phishing","Password spraying","Valid credential abuse","PowerShell execution","Shamoon wiper deployment","Data destruction"], notableAttacks: ["Shamoon Saudi Aramco 35K machines (2012)","Shamoon 2 (2016)","US defence password spray (2023)"], description: "Iranian group. Shamoon wiper destroyed 35,000 workstations at Saudi Aramco." },
  { id: "scattered-spider", name: "Scattered Spider", aliases: ["UNC3944","Octo Tempest","0ktapus"], origin: "USA/UK", type: "cybercrime", motivation: "Extortion", targets: ["Telecoms","Hospitality","Finance","Technology"], activeSince: "2022", ttps: ["T1566.004","T1598.004","T1078","T1199","T1621","T1550","T1486"], ttpDescriptions: ["Vishing helpdesks","Social engineering MFA resets","Valid account takeover","MSP trust exploitation","MFA fatigue bombing","Session token replay","ALPHV ransomware"], notableAttacks: ["MGM $100M+ (2023)","Caesars $15M ransom (2023)","Twilio/0ktapus (2022)"], description: "Young criminals who social-engineer helpdesks. 10-min call gave them MGM Resorts." },
  { id: "lockbit", name: "LockBit", aliases: ["LockBit 3.0","LockBit Black"], origin: "Russia", type: "cybercrime", motivation: "RaaS", targets: ["Healthcare","Government","Manufacturing","Finance","Education"], activeSince: "2019", ttps: ["T1190","T1133","T1078","T1486","T1490","T1048","T1562.001","T1021.001"], ttpDescriptions: ["Public-facing exploitation","RDP/VPN access","Purchased credentials","File encryption","Backup deletion","Data exfiltration","Security tool disabling","RDP lateral movement"], notableAttacks: ["Royal Mail (2023)","Boeing (2023)","ICBC (2023)"], description: "Most prolific RaaS. Disrupted by Operation Cronos (2024)." },
  { id: "clop", name: "CL0P", aliases: ["TA505","FIN11","Lace Tempest"], origin: "Russia/Ukraine", type: "cybercrime", motivation: "Mass exploitation", targets: ["All sectors"], activeSince: "2019", ttps: ["T1190","T1210","T1005","T1048","T1486","T1059.001"], ttpDescriptions: ["Zero-day file transfer exploitation","Remote service exploitation","Mass data collection","Mass exfiltration","Encryption","Automated PowerShell"], notableAttacks: ["MOVEit 2500+ orgs (2023)","GoAnywhere (2023)","Accellion (2021)"], description: "Mass exploitation of file transfer tools. MOVEit hit Shell, BBC, US government." },
  { id: "alphv", name: "ALPHV/BlackCat", aliases: ["BlackCat","Noberus"], origin: "Russia", type: "cybercrime", motivation: "RaaS", targets: ["Healthcare","Finance","Government","Hospitality"], activeSince: "2021", ttps: ["T1190","T1078","T1486","T1490","T1048","T1059","T1562"], ttpDescriptions: ["Public-facing exploitation","Stolen credentials","Rust ransomware","Backup deletion","Double extortion","Multi-language scripting","Security tool tampering"], notableAttacks: ["Change Healthcare (2024)","MGM via Scattered Spider (2023)","Reddit (2023)"], description: "First major Rust ransomware. Change Healthcare paralysed US healthcare payments." },
  { id: "rhysida", name: "Rhysida", aliases: ["Vice Society successor"], origin: "Unknown", type: "cybercrime", motivation: "RaaS targeting public sector", targets: ["Healthcare","Education","Government","Libraries"], activeSince: "2023", ttps: ["T1190","T1133","T1078","T1486","T1490","T1048"], ttpDescriptions: ["Public-facing exploitation","VPN/RDP access","Valid credentials","ChaCha20+RSA encryption","Backup destruction","Double extortion"], notableAttacks: ["British Library (2023)","17 US hospitals (2023)","Chilean Army (2023)"], description: "Targets public institutions. Destroyed the British Library catalogue." },
  { id: "killnet", name: "KillNet", aliases: ["Anonymous Russia"], origin: "Russia", type: "hacktivist", motivation: "Pro-Russian disruption", targets: ["Government","Aviation","Healthcare","Finance"], activeSince: "2022", ttps: ["T1498","T1499","T1583","T1589"], ttpDescriptions: ["DDoS on web infrastructure","Application layer flooding","Rented botnets","OSINT reconnaissance"], notableAttacks: ["US airport websites (2022)","European Parliament (2022)","NATO sites (2022-23)"], description: "Pro-Russian hacktivists. DDoS against NATO countries. Low sophistication, high volume." },
];

export function getActorById(id: string) { return THREAT_ACTORS.find(a => a.id === id); }
export function searchActors(q: string) { const s = q.toLowerCase(); return THREAT_ACTORS.filter(a => a.name.toLowerCase().includes(s) || a.aliases.some(al => al.toLowerCase().includes(s)) || a.origin.toLowerCase().includes(s) || a.targets.some(t => t.toLowerCase().includes(s))); }

export function getActorsByMotivation(m: string) { return THREAT_ACTORS.filter(a => a.motivation === m); }

export function buildActorContext(actor: ThreatActor): string {
  return `
THREAT ACTOR PROFILE:
Name: ${actor.name} (${actor.aliases.join(", ")})
Origin: ${actor.origin} | Motivation: ${actor.motivation} | Active Since: ${actor.activeSince}
Description: ${actor.description}
Targets: ${actor.targets.join(", ")}
TTPs: ${actor.ttpDescriptions.join(", ")}
MITRE Techniques: ${actor.ttps.join(", ")}
Notable Incidents: ${actor.notableAttacks.join("; ")}

IMPORTANT: This exercise MUST simulate an attack by ${actor.name}. Use their KNOWN TTPs, tools, and patterns. Reference their real operations. The scenario should feel like this specific group is targeting the organisation.`;
}
