export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { getAuthUser } from "@/lib/auth-helpers";
import { db } from "@/lib/db";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ sessionId: string }> }
) {
  const user = await getAuthUser();
  if (!user?.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { sessionId } = await params;

  const session = await db.ttxSession.findFirst({
    where: { id: sessionId, orgId: user.orgId },
    select: { title: true, theme: true, scenario: true, organization: { select: { name: true } } },
  });
  if (!session) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const scenario = session.scenario as any;
  if (!scenario?.stages) return NextResponse.json({ error: "No scenario" }, { status: 400 });

  const doc = await PDFDocument.create();
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const teal = rgb(0.078, 0.722, 0.604);
  const black = rgb(0, 0, 0);
  const gray = rgb(0.4, 0.4, 0.4);

  let page = doc.addPage([595.28, 841.89]); // A4 portrait
  let y = 780;
  const margin = 50;
  const pw = 595.28 - margin * 2;

  function checkPage() { if (y < 80) { page = doc.addPage([595.28, 841.89]); y = 780; } }

  function drawWrapped(text: string, font: typeof helvetica, size: number, color: ReturnType<typeof rgb>, indent = 0) {
    const words = text.split(" ");
    let line = "";
    for (const word of words) {
      const test = line ? line + " " + word : word;
      if (font.widthOfTextAtSize(test, size) > pw - indent) {
        checkPage();
        page.drawText(line, { x: margin + indent, y, font, size, color });
        y -= size + 4;
        line = word;
      } else { line = test; }
    }
    if (line) { checkPage(); page.drawText(line, { x: margin + indent, y, font, size, color }); y -= size + 4; }
  }

  // Header
  page.drawText("ThreatCast", { x: margin, y, font: helveticaBold, size: 20, color: teal }); y -= 25;
  page.drawText("Incident Response Playbook", { x: margin, y, font: helveticaBold, size: 16, color: black }); y -= 18;
  page.drawText(session.title, { x: margin, y, font: helvetica, size: 11, color: gray }); y -= 14;
  page.drawText(`${session.organization?.name || ""} | ${session.theme}`, { x: margin, y, font: helvetica, size: 10, color: gray }); y -= 20;
  page.drawLine({ start: { x: margin, y }, end: { x: 595.28 - margin, y }, thickness: 1, color: teal }); y -= 25;

  const sectionNames = ["Detection & Identification", "Containment", "Eradication & Recovery"];
  const stages = scenario.stages || [];

  stages.forEach((stage: any, i: number) => {
    checkPage();
    const title = i < 3 ? `${i + 1}. ${sectionNames[i]}` : `${i + 1}. ${stage.title || "Additional Steps"}`;
    page.drawText(title, { x: margin, y, font: helveticaBold, size: 13, color: teal }); y -= 18;

    if (stage.narrative) { drawWrapped(stage.narrative, helvetica, 9, gray); y -= 8; }

    if (stage.questions?.length) {
      page.drawText("Response Actions:", { x: margin, y, font: helveticaBold, size: 9, color: gray }); y -= 14;
      stage.questions.forEach((q: any) => {
        const correct = q.options?.find((o: any) => o.isCorrect);
        checkPage();
        drawWrapped(`> ${q.question}`, helvetica, 8, black, 10);
        if (correct) { drawWrapped(correct.text, helvetica, 8, teal, 20); }
        y -= 4;
      });
    }
    y -= 12;
  });

  checkPage();
  page.drawText(`Generated by ThreatCast | threatcast.io | ${new Date().toLocaleDateString("en-GB")}`, { x: margin, y: 40, font: helvetica, size: 7, color: gray });

  const pdfBytes = await doc.save();
  return new NextResponse(new Uint8Array(pdfBytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="playbook-${sessionId.slice(-8)}.pdf"`,
    },
  });
}
