export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { getAuthUser } from "@/lib/auth-helpers";
import { db } from "@/lib/db";
import PDFDocument from "pdfkit";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ sessionId: string }> }
) {
  const user = await getAuthUser();
  if (!user?.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { sessionId } = await params;

  const session = await db.ttxSession.findFirst({
    where: { id: sessionId, orgId: user.orgId },
    select: { title: true, theme: true, scenario: true, organization: { select: { name: true } } },
  });
  if (!session) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const scenario = session.scenario as any;
  if (!scenario?.stages) return NextResponse.json({ error: "No scenario" }, { status: 400 });

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  // Header
  doc.fontSize(24).fillColor("#14b89a").text("ThreatCast", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(18).fillColor("#333").text(`Incident Response Playbook`, { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(12).fillColor("#666").text(session.title, { align: "center" });
  doc.text(`${session.organization?.name || ""} · ${session.theme}`, { align: "center" });
  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#14b89a").lineWidth(1).stroke();
  doc.moveDown(1);

  // Sections
  const stages = scenario.stages || [];
  const sectionNames = ["Detection & Identification", "Containment", "Eradication & Recovery"];

  stages.forEach((stage: any, i: number) => {
    if (doc.y > 700) doc.addPage();
    const title = i < 3 ? `${i + 1}. ${sectionNames[i]}` : `${i + 1}. ${stage.title || "Additional Steps"}`;
    doc.fontSize(14).fillColor("#14b89a").text(title);
    doc.moveDown(0.3);
    if (stage.narrative) {
      doc.fontSize(10).fillColor("#333").text(stage.narrative, { lineGap: 2 });
      doc.moveDown(0.5);
    }
    if (stage.questions?.length) {
      doc.fontSize(10).fillColor("#666").text("Response Actions:", { underline: true });
      doc.moveDown(0.3);
      stage.questions.forEach((q: any) => {
        const correct = q.options?.find((o: any) => o.isCorrect);
        if (doc.y > 720) doc.addPage();
        doc.fontSize(9).fillColor("#333").text(`→ ${q.question}`, { indent: 15 });
        if (correct) doc.fontSize(9).fillColor("#14b89a").text(`   ${correct.text}`, { indent: 20 });
        doc.moveDown(0.3);
      });
    }
    doc.moveDown(0.8);
  });

  // MITRE
  if (scenario.mitreAttackIds?.length) {
    doc.fontSize(10).fillColor("#666").text(`MITRE ATT&CK: ${scenario.mitreAttackIds.join(", ")}`);
  }

  doc.fontSize(8).fillColor("#999").text(`\nGenerated by ThreatCast · threatcast.io · ${new Date().toLocaleDateString("en-GB")}`, { align: "center" });
  doc.end();

  const pdf = await done;
  return new NextResponse(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="playbook-${sessionId.slice(-8)}.pdf"`,
    },
  });
}
