export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { getAuthUser } from "@/lib/auth-helpers";
import { db } from "@/lib/db";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } from "docx";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ sessionId: string }> }
) {
  const user = await getAuthUser();
  if (!user?.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { sessionId } = await params;

  const session = await db.ttxSession.findFirst({
    where: { id: sessionId, orgId: user.orgId },
    select: { title: true, theme: true, scenario: true, organization: { select: { name: true } } },
  });
  if (!session) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const scenario = session.scenario as any;
  if (!scenario?.stages) return NextResponse.json({ error: "No scenario" }, { status: 400 });

  const stages = scenario.stages || [];
  const sectionNames = ["Detection & Identification", "Containment", "Eradication & Recovery"];

  const children: Paragraph[] = [
    new Paragraph({ children: [new TextRun({ text: "ThreatCast", bold: true, size: 36, color: "14b89a" })], alignment: "center" as any }),
    new Paragraph({ children: [new TextRun({ text: "Incident Response Playbook", size: 28 })], alignment: "center" as any, spacing: { after: 200 } }),
    new Paragraph({ children: [new TextRun({ text: session.title, italics: true, size: 22 })], alignment: "center" as any }),
    new Paragraph({ children: [new TextRun({ text: `${session.organization?.name || ""} · ${session.theme}`, size: 18, color: "666666" })], alignment: "center" as any, spacing: { after: 400 } }),
    new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "14b89a" } }, spacing: { after: 300 } }),
  ];

  stages.forEach((stage: any, i: number) => {
    const title = i < 3 ? `${i + 1}. ${sectionNames[i]}` : `${i + 1}. ${stage.title || "Additional Steps"}`;
    children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_2, spacing: { before: 300 } }));

    if (stage.narrative) {
      children.push(new Paragraph({ children: [new TextRun({ text: stage.narrative, size: 20 })], spacing: { after: 200 } }));
    }

    if (stage.questions?.length) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Response Actions:", bold: true, size: 20 })], spacing: { before: 100 } }));
      stage.questions.forEach((q: any) => {
        const correct = q.options?.find((o: any) => o.isCorrect);
        children.push(new Paragraph({
          children: [new TextRun({ text: `→ ${q.question}`, size: 18 })],
          indent: { left: 360 }, spacing: { before: 100 },
        }));
        if (correct) {
          children.push(new Paragraph({
            children: [new TextRun({ text: correct.text, size: 18, color: "14b89a", italics: true })],
            indent: { left: 720 },
          }));
        }
      });
    }
  });

  if (scenario.mitreAttackIds?.length) {
    children.push(new Paragraph({ spacing: { before: 400 } }));
    children.push(new Paragraph({ children: [new TextRun({ text: `MITRE ATT&CK: ${scenario.mitreAttackIds.join(", ")}`, size: 18, color: "666666" })] }));
  }

  children.push(new Paragraph({ children: [new TextRun({ text: `Generated by ThreatCast · threatcast.io · ${new Date().toLocaleDateString("en-GB")}`, size: 16, color: "999999" })], spacing: { before: 400 }, alignment: "center" as any }));

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="playbook-${sessionId.slice(-8)}.docx"`,
    },
  });
}
