import Link from "next/link";
export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 py-12 max-w-3xl mx-auto">
      <Link href="/" className="text-gray-500 text-sm hover:text-white mb-8 inline-block">← Back to ThreatCast</Link>
      <h1 className="font-display text-3xl font-bold text-white mb-6">Terms of Service</h1>
      <p className="text-gray-500 text-xs mb-8">Last updated: April 2026</p>
      <div className="prose prose-invert prose-sm max-w-none space-y-4 text-gray-400 text-sm leading-relaxed">
        <h2 className="text-white text-lg font-semibold mt-6">1. Agreement to Terms</h2>
        <p>By accessing or using ThreatCast (&ldquo;the Service&rdquo;), operated by ThreatCast Ltd, Glasgow, Scotland, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        <h2 className="text-white text-lg font-semibold mt-6">2. Description of Service</h2>
        <p>ThreatCast provides AI-powered cybersecurity tabletop exercise simulations, including scenario generation, multiplayer exercises, playbook generation, SIEM/XDR integration, performance tracking, and compliance evidence mapping.</p>
        <h2 className="text-white text-lg font-semibold mt-6">3. Accounts</h2>
        <p>You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and all activities under your account. Notify us immediately of any unauthorised use.</p>
        <h2 className="text-white text-lg font-semibold mt-6">4. Subscriptions and Billing</h2>
        <p>Paid plans are billed monthly. You may cancel at any time; your access continues until the end of the current billing period. Refunds are not provided for partial months. Prices may change with 30 days notice.</p>
        <h2 className="text-white text-lg font-semibold mt-6">5. Acceptable Use</h2>
        <p>You agree not to: reverse engineer the Service; use it to develop competing products; share API keys; submit malicious content; or use generated scenarios to cause harm. Generated exercises are fictional and should not be used as real incident response procedures without professional review.</p>
        <h2 className="text-white text-lg font-semibold mt-6">6. Data and Security</h2>
        <p>Exercise data, SIEM credentials, and user information are encrypted at rest and in transit. SIEM/XDR credentials are stored encrypted and never shared. We do not access your security tool data except to generate alerts for exercises at your request.</p>
        <h2 className="text-white text-lg font-semibold mt-6">7. AI-Generated Content</h2>
        <p>Scenarios are generated by AI and may contain inaccuracies. They are educational simulations, not professional security advice. ThreatCast is not liable for decisions made based on exercise content.</p>
        <h2 className="text-white text-lg font-semibold mt-6">8. Intellectual Property</h2>
        <p>You retain ownership of your data. Generated playbooks and certificates are licensed to you for internal use. The ThreatCast platform, branding, and technology remain our intellectual property.</p>
        <h2 className="text-white text-lg font-semibold mt-6">9. Limitation of Liability</h2>
        <p>ThreatCast is provided &ldquo;as is&rdquo;. We are not liable for indirect, incidental, or consequential damages. Our total liability is limited to the amount paid by you in the 12 months preceding the claim.</p>
        <h2 className="text-white text-lg font-semibold mt-6">10. Governing Law</h2>
        <p>These Terms are governed by the laws of Scotland. Disputes shall be resolved in the courts of Glasgow.</p>
        <h2 className="text-white text-lg font-semibold mt-6">11. Contact</h2>
        <p>Questions about these Terms? Email support@threatcast.io.</p>
      </div>
    </div>
  );
}
