export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="font-display text-3xl font-bold text-white mb-8">Terms of Service</h1>
      <div className="prose prose-invert prose-sm text-gray-400 space-y-6">
        <p className="text-gray-300">Last updated: April 2026</p>
        <h2 className="text-white text-lg font-semibold">1. Acceptance of Terms</h2>
        <p>By accessing or using ThreatCast (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        <h2 className="text-white text-lg font-semibold">2. Description of Service</h2>
        <p>ThreatCast provides AI-powered cybersecurity tabletop exercise generation, team performance tracking, compliance evidence mapping, and related services for security teams.</p>
        <h2 className="text-white text-lg font-semibold">3. Account Registration</h2>
        <p>You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your password and for all activities under your account.</p>
        <h2 className="text-white text-lg font-semibold">4. Acceptable Use</h2>
        <p>You agree not to: (a) use the Service to generate content that promotes illegal activity; (b) attempt to gain unauthorised access to other accounts; (c) reverse engineer, decompile, or disassemble the Service; (d) resell or redistribute the Service without permission.</p>
        <h2 className="text-white text-lg font-semibold">5. Intellectual Property</h2>
        <p>Exercise scenarios, reports, and playbooks generated by the Service are licensed to your organisation for internal use. ThreatCast retains ownership of the platform, algorithms, and anonymised aggregate data.</p>
        <h2 className="text-white text-lg font-semibold">6. Data Protection</h2>
        <p>We process personal data in accordance with our Privacy Policy and applicable data protection laws including UK GDPR, EU GDPR, and the Data Protection Act 2018.</p>
        <h2 className="text-white text-lg font-semibold">7. Service Availability</h2>
        <p>We aim for 99.9% uptime but do not guarantee uninterrupted access. We may perform maintenance with reasonable notice.</p>
        <h2 className="text-white text-lg font-semibold">8. Limitation of Liability</h2>
        <p>ThreatCast shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the fees paid by you in the 12 months preceding the claim.</p>
        <h2 className="text-white text-lg font-semibold">9. Termination</h2>
        <p>Either party may terminate the agreement with 30 days&apos; written notice. Upon termination, you may export your data within 30 days.</p>
        <h2 className="text-white text-lg font-semibold">10. Governing Law</h2>
        <p>These Terms are governed by the laws of Scotland, United Kingdom. Disputes shall be subject to the exclusive jurisdiction of the Scottish courts.</p>
        <p className="text-gray-500 text-xs mt-8">ThreatCast Ltd · Glasgow, United Kingdom · support@threatcast.io</p>
      </div>
    </div>
  );
}
